# Locally override default configurations
#
# This file overrides configurations set in `config/config.defaults.yml`.
# Keep in mind that environment variables override setting in this file.
#
# Usage:
#
# Copy this file from `config/config.example.yml` to `config/config.yml`
#

development:
  # Add local `development` environment configuration overrides here
  domain: <%= ENV['DNS_DOMAIN']  %>
test:
  # Add local `test` environment configuration overrides here
  domain: <%= ENV['DNS_DOMAIN']  %>
staging:
  # Add local `staging` environment configuration overrides here
  domain: <%= ENV['DNS_DOMAIN']  %>
production:
  # Add local `production` environment configuration overrides here
  domain: <%= ENV['DNS_DOMAIN']  %>
